export enum Errors {
    BAD_REQUEST_ERROR = "BAD_REQUEST_ERROR",
    NOT_FOUND_ERROR = "NOT_FOUND_ERROR",
    CONFLICT_ERROR = "CONFLICT_ERROR",
    UNDEFINED_ERROR = "UNDEFINED_ERROR",
    ERR_NETWORK = "ERR_NETWORK",
    UNTYPED_ERROR = "UNTYPED_ERROR",
    UNAUTHORIZED_ERROR = "UNAUTHORIZED_ERROR",
    NO_ACCESS_ERROR = "NO_ACCESS_ERROR",
    GATEWAY_TIMEOUT_ERROR = "GATEWAY_TIMEOUT_ERROR",
    PAYLOAD_TOO_LARGE_ERROR = "PAYLOAD_TOO_LARGE_ERROR"
}
